/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewSisXerox.Paines;

import NewSisXerox.Classes.Validador;
import NewSisXerox.Classes.UpperCaseField;
import NewSisXerox.DAO.GenericDAO;
import NewSisXerox.Entity.Curso;
import javax.swing.JOptionPane;
import NewSisXerox.Entity.Instituicao;
import NewSisXerox.Tabelas.tabCurso;
import java.awt.event.KeyEvent;
import java.util.List;

/**
 *
 * @author Allan
 */
public class JPCurso extends javax.swing.JPanel {

    /**
     * Creates new form JPInstituica
     */
    private Curso curso;
    private tabCurso tabCurso;

    public JPCurso() {
        initComponents();
        carregaCombo();
        tabCurso = new tabCurso();
        jtCurso.setModel(tabCurso);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void limparDados() {
        jtfCurso.setText("");
        jcInstituicao.setSelectedItem(null);
    }

    public void carregaCombo() {
        jcInstituicao.removeAllItems();//removendo tds os itens da combo
        jcInstituicao.addItem(null);
        try {
            List<Instituicao> lstInstituicao = GenericDAO.getInstance().getList(Instituicao.class,
                    "FROM Instituicao nmInstituicao"); //tem q ta = o nome da classe criada
            for (Instituicao a : lstInstituicao) {
                jcInstituicao.addItem(a);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar Instituição!" + "\n" + e.getMessage());
        }
    }

    public void carregaTabela() {
        try {
            List l = GenericDAO.getInstance().getList(Curso.class,
                    "FROM Curso nmCurso");  // consulta no banco
            tabCurso.setDados(l);
            jtCurso.updateUI();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar tabela de Cursos!" + "\n" + e.getMessage());
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscaCurso = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCurso = new javax.swing.JTable();
        jbSelecionarCurso = new javax.swing.JButton();
        jlCurso = new javax.swing.JLabel();
        jtfCurso = new UpperCaseField();
        jbGravar = new javax.swing.JButton();
        jlInstituicao = new javax.swing.JLabel();
        jcInstituicao = new javax.swing.JComboBox();

        BuscaCurso.setTitle("Busca Curso");
        BuscaCurso.setMinimumSize(new java.awt.Dimension(500, 335));

        jtCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtCurso);

        jbSelecionarCurso.setText("Selecionar");
        jbSelecionarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelecionarCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuscaCursoLayout = new javax.swing.GroupLayout(BuscaCurso.getContentPane());
        BuscaCurso.getContentPane().setLayout(BuscaCursoLayout);
        BuscaCursoLayout.setHorizontalGroup(
            BuscaCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscaCursoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSelecionarCurso)
                .addContainerGap())
        );
        BuscaCursoLayout.setVerticalGroup(
            BuscaCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaCursoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSelecionarCurso)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jlCurso.setText("Curso:");

        jtfCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCursoKeyPressed(evt);
            }
        });

        jbGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewSisXerox/Imagens/Salvar - 16.png"))); // NOI18N
        jbGravar.setText("Gravar");
        jbGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGravarActionPerformed(evt);
            }
        });

        jlInstituicao.setText("Instiuição:");

        jcInstituicao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbGravar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlCurso)
                        .addGap(22, 22, 22)
                        .addComponent(jtfCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlInstituicao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcInstituicao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCurso)
                    .addComponent(jtfCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlInstituicao)
                    .addComponent(jcInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbGravar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGravarActionPerformed
        if (Validador.vldStringMinMax(jtfCurso.getText(), 3, 50) == false) {
            JOptionPane.showMessageDialog(this, "Informe o nome do Curso!");
            jtfCurso.requestFocus();
            return;
        }
        try {
            if (curso == null) {
                curso = new Curso();
            }
            curso.setNmCurso(jtfCurso.getText());
            curso.setCdInstituicao((Instituicao) jcInstituicao.getSelectedItem());
            GenericDAO.getInstance().startTransaction();
            GenericDAO.getInstance().persist(curso);
            GenericDAO.getInstance().commit();
            JOptionPane.showMessageDialog(null, "Instituição " + jtfCurso.getText() + " gravada com Sucesso!");
            limparDados();

        } catch (Exception ex) {
            GenericDAO.getInstance().rollback();
            JOptionPane.showMessageDialog(null, "Instituição já existente!" + ex.getMessage());
            limparDados();
        }
        jtfCurso.requestFocus();
    }//GEN-LAST:event_jbGravarActionPerformed

    private void jbSelecionarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelecionarCursoActionPerformed
        try {
            //pegando a opção selecionada na grade
            curso = (Curso) tabCurso.getDadoAt(jtCurso.getSelectedRow());
            if (curso != null) {
                jtfCurso.setText(curso.getNmCurso());
                jcInstituicao.setSelectedItem(curso.getCdInstituicao());
                BuscaCurso.dispose();
            }
        } catch (Throwable t) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar a Curso/Instituição!" + "\n" + t.getMessage());
            limparDados();
        }
    }//GEN-LAST:event_jbSelecionarCursoActionPerformed

    private void jtfCursoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCursoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            carregaTabela();
            BuscaCurso.show();
            BuscaCurso.setLocationRelativeTo(this);//seta a posição da tela 
        }
    }//GEN-LAST:event_jtfCursoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog BuscaCurso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbGravar;
    private javax.swing.JButton jbSelecionarCurso;
    private javax.swing.JComboBox jcInstituicao;
    private javax.swing.JLabel jlCurso;
    private javax.swing.JLabel jlInstituicao;
    private javax.swing.JTable jtCurso;
    private javax.swing.JTextField jtfCurso;
    // End of variables declaration//GEN-END:variables
}
