/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewSisXerox.Paines;

import NewSisXerox.Classes.Validador;
import NewSisXerox.Classes.UpperCaseField;
import NewSisXerox.DAO.GenericDAO;
import javax.swing.JOptionPane;
import NewSisXerox.Entity.Instituicao;
import NewSisXerox.Tabelas.tabInstituicao;
import java.awt.event.KeyEvent;
import java.util.List;

/**
 *
 * @author Allan
 */
public class JPInstituicao extends javax.swing.JPanel {

    /**
     * Creates new form JPInstituica
     */
    private Instituicao ins;
    private tabInstituicao tabInstituicao;

    public JPInstituicao() {
        initComponents();
        tabInstituicao = new tabInstituicao();
        jtInstituicao.setModel(tabInstituicao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void limparDados() {
        jtfInstituicao.setText("");
    }

    public void carregaTabela() {
        try {
            List l = GenericDAO.getInstance().getList(Instituicao.class,
                    "FROM Instituicao nmInstituicao");  // consulta no banco
            tabInstituicao.setDados(l);
            jtInstituicao.updateUI();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar a tabela Instituição!" + e.getMessage());
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscaInstituicao = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtInstituicao = new javax.swing.JTable();
        jbSelecionarInstituicao = new javax.swing.JButton();
        jlInstituicao = new javax.swing.JLabel();
        jtfInstituicao = new UpperCaseField();
        jbGravar = new javax.swing.JButton();

        BuscaInstituicao.setTitle("Busca Instituição");
        BuscaInstituicao.setMinimumSize(new java.awt.Dimension(500, 335));

        jtInstituicao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtInstituicao);

        jbSelecionarInstituicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewSisXerox/Imagens/selecionar - 16.png"))); // NOI18N
        jbSelecionarInstituicao.setText("Selecionar");
        jbSelecionarInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelecionarInstituicaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuscaInstituicaoLayout = new javax.swing.GroupLayout(BuscaInstituicao.getContentPane());
        BuscaInstituicao.getContentPane().setLayout(BuscaInstituicaoLayout);
        BuscaInstituicaoLayout.setHorizontalGroup(
            BuscaInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscaInstituicaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSelecionarInstituicao)
                .addContainerGap())
        );
        BuscaInstituicaoLayout.setVerticalGroup(
            BuscaInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaInstituicaoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSelecionarInstituicao)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jlInstituicao.setText("Instiuição:");

        jtfInstituicao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfInstituicaoKeyPressed(evt);
            }
        });

        jbGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewSisXerox/Imagens/Salvar - 16.png"))); // NOI18N
        jbGravar.setText("Gravar");
        jbGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbGravar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlInstituicao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlInstituicao)
                    .addComponent(jtfInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbGravar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGravarActionPerformed
        if (Validador.vldStringMinMax(jtfInstituicao.getText(), 3, 50) == false) {
            JOptionPane.showMessageDialog(this, "Informe o nome Instituição!");
            jtfInstituicao.requestFocus();
            return;
        }
        try {
            if (ins == null) {
                ins = new Instituicao();
            }
            ins.setNmInstituicao(jtfInstituicao.getText());
            GenericDAO.getInstance().startTransaction();
            GenericDAO.getInstance().persist(ins);
            GenericDAO.getInstance().commit();
            JOptionPane.showMessageDialog(null, "Instituição " + jtfInstituicao.getText() + " gravada com Sucesso!");
            limparDados();

        } catch (Exception ex) {
            GenericDAO.getInstance().rollback();
            JOptionPane.showMessageDialog(null, "Instituição já existente!" + ex.getMessage());
            limparDados();
        }
        jtfInstituicao.requestFocus();
    }//GEN-LAST:event_jbGravarActionPerformed

    private void jtfInstituicaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfInstituicaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            carregaTabela();
            BuscaInstituicao.show();
            BuscaInstituicao.setLocationRelativeTo(this);//seta a posição da tela 
        }
    }//GEN-LAST:event_jtfInstituicaoKeyPressed

    private void jbSelecionarInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelecionarInstituicaoActionPerformed
        try {
            //pegando a opção selecionada na grade
            ins = (Instituicao) tabInstituicao.getDadoAt(jtInstituicao.getSelectedRow());
            if (ins != null) {
                jtfInstituicao.setText(ins.getNmInstituicao());
                BuscaInstituicao.dispose();
            }
        } catch (Throwable t) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar a Instituição!" + "\n" + t.getMessage());
            limparDados();
        }
    }//GEN-LAST:event_jbSelecionarInstituicaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog BuscaInstituicao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbGravar;
    private javax.swing.JButton jbSelecionarInstituicao;
    private javax.swing.JLabel jlInstituicao;
    private javax.swing.JTable jtInstituicao;
    private javax.swing.JTextField jtfInstituicao;
    // End of variables declaration//GEN-END:variables
}
