/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewSisXerox.Paines;

import java.awt.event.KeyEvent;
import NewSisXerox.Classes.UpperCaseField;

/**
 *
 * @author Allan
 */
public class JPModeloPainel extends javax.swing.JPanel {

    /**
     * Creates new form JPCurso
     */
    public JPModeloPainel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscaModeloPaine = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtModeloPainel = new javax.swing.JTable();
        jbSelecionarModeloPainel = new javax.swing.JButton();
        jlModeloPaine = new javax.swing.JLabel();
        jtfModeloPaine = new UpperCaseField();
        jbGravarModeloPaine = new javax.swing.JButton();

        BuscaModeloPaine.setTitle("Busca");
        BuscaModeloPaine.setMinimumSize(new java.awt.Dimension(500, 335));

        jtModeloPainel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtModeloPainel);

        jbSelecionarModeloPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisXerox/Imagens/selecionar - 16.png"))); // NOI18N
        jbSelecionarModeloPainel.setText("Selecionar");

        javax.swing.GroupLayout BuscaModeloPaineLayout = new javax.swing.GroupLayout(BuscaModeloPaine.getContentPane());
        BuscaModeloPaine.getContentPane().setLayout(BuscaModeloPaineLayout);
        BuscaModeloPaineLayout.setHorizontalGroup(
            BuscaModeloPaineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscaModeloPaineLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSelecionarModeloPainel)
                .addContainerGap())
        );
        BuscaModeloPaineLayout.setVerticalGroup(
            BuscaModeloPaineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaModeloPaineLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSelecionarModeloPainel)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        setLayout(null);

        jlModeloPaine.setText("Modelo:");
        add(jlModeloPaine);
        jlModeloPaine.setBounds(10, 22, 40, 14);

        jtfModeloPaine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfModeloPaineKeyPressed(evt);
            }
        });
        add(jtfModeloPaine);
        jtfModeloPaine.setBounds(50, 19, 300, 20);

        jbGravarModeloPaine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewSisXerox/Imagens/Salvar - 16.png"))); // NOI18N
        jbGravarModeloPaine.setText("Gravar");
        add(jbGravarModeloPaine);
        jbGravarModeloPaine.setBounds(265, 45, 85, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfModeloPaineKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfModeloPaineKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BuscaModeloPaine.show();
            BuscaModeloPaine.setLocationRelativeTo(this);//seta a posição da tela 
        }
    }//GEN-LAST:event_jtfModeloPaineKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog BuscaModeloPaine;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbGravarModeloPaine;
    private javax.swing.JButton jbSelecionarModeloPainel;
    private javax.swing.JLabel jlModeloPaine;
    private javax.swing.JTable jtModeloPainel;
    private javax.swing.JTextField jtfModeloPaine;
    // End of variables declaration//GEN-END:variables
}
