/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewSisXerox.Paines;

import NewSisXerox.Classes.Validador;
import NewSisXerox.Classes.UpperCaseField;
import NewSisXerox.Classes.JtextFieldSomenteLetras;
import NewSisXerox.DAO.GenericDAO;
import javax.swing.JOptionPane;
import NewSisXerox.Entity.Marca;
import NewSisXerox.Entity.Modelo;
import NewSisXerox.Tabelas.tabModelo;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Allan
 */
public class JPModelo extends javax.swing.JPanel {

    /**
     * Creates new form JPInstituica
     */
    private Modelo modelo;
    private tabModelo tabmodelo;
    Icon alerta = new ImageIcon(getToolkit().createImage(getClass().getResource("/NewSisXerox/Imagens/Warning-48.png")));
    Icon erro = new ImageIcon(getToolkit().createImage(getClass().getResource("/NewSisXerox/Imagens/Error-48.png")));
    Icon sucesso = new ImageIcon(getToolkit().createImage(getClass().getResource("/NewSisXerox/Imagens/Default-48.png")));

    public JPModelo() {
        initComponents();
        carregaCombo();
        tabmodelo = new tabModelo();
        jtBusca.setModel(tabmodelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void limparDados() {
        jtfModelo.setText("");
        jcModelo.setSelectedItem(null);
    }

    public void carregaCombo() {
        jcModelo.removeAllItems();//removendo tds os itens da combo
        jcModelo.addItem(null);
        try {
            List<Marca> lstMarca = GenericDAO.getInstance().getList(Marca.class,
                    "FROM Marca nmMarca"); //tem q ta = o nome da classe criada
            for (Marca a : lstMarca) {
                jcModelo.addItem(a);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar as Marcas!" + "\n" + ex.getClass().getSimpleName() + "\n" + ex.getMessage(), "ATENÇÃO", JOptionPane.ERROR_MESSAGE, erro);
        }
    }

    public void carregaTabela() {
        try {
            List l = GenericDAO.getInstance().getList(Modelo.class,
                    "FROM Modelo nmModelo");  // consulta no banco
            tabmodelo.setDados(l);
            jtBusca.updateUI();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar Modelo!" + "\n" + ex.getClass().getSimpleName() + "\n" + ex.getMessage(), "ATENÇÃO", JOptionPane.ERROR_MESSAGE, erro);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Busca = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtBusca = new javax.swing.JTable();
        jbSelecionarCurso = new javax.swing.JButton();
        jlmodelo = new javax.swing.JLabel();
        jtfModelo = new UpperCaseField();
        jbGravar = new javax.swing.JButton();
        jMarca = new javax.swing.JLabel();
        jcModelo = new javax.swing.JComboBox();

        Busca.setTitle("Busca");
        Busca.setMinimumSize(new java.awt.Dimension(500, 335));

        jtBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtBusca);

        jbSelecionarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewSisXerox/Imagens/selecionar - 16.png"))); // NOI18N
        jbSelecionarCurso.setText("Selecionar");
        jbSelecionarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelecionarCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuscaLayout = new javax.swing.GroupLayout(Busca.getContentPane());
        Busca.getContentPane().setLayout(BuscaLayout);
        BuscaLayout.setHorizontalGroup(
            BuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSelecionarCurso)
                .addContainerGap())
        );
        BuscaLayout.setVerticalGroup(
            BuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSelecionarCurso)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jlmodelo.setText("Marca:");

        jtfModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfModeloKeyPressed(evt);
            }
        });

        jbGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewSisXerox/Imagens/Salvar - 16.png"))); // NOI18N
        jbGravar.setText("Gravar");
        jbGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGravarActionPerformed(evt);
            }
        });

        jMarca.setText("Modelo:");

        jcModelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbGravar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlmodelo)
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jMarca)
                                .addGap(17, 17, 17)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcModelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlmodelo)
                    .addComponent(jtfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMarca)
                    .addComponent(jcModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbGravar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGravarActionPerformed

        if (Validador.vldStringMinMax(jtfModelo.getText(), 3, 50) == false) {
            JOptionPane.showMessageDialog(this, "Informe o nome do modelo!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE, alerta);
            jtfModelo.requestFocus();
            return;
        }
        if (jcModelo.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma Marca!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE, alerta);
            jcModelo.requestFocus();
            return;
        }
        try {
            if (modelo == null) {
                modelo = new Modelo();
            }
            modelo.setNmModelo(jtfModelo.getText());
            modelo.setCdMarca((Marca) jcModelo.getSelectedItem());
            GenericDAO.getInstance().startTransaction();
            GenericDAO.getInstance().persist(modelo);
            GenericDAO.getInstance().commit();
            JOptionPane.showMessageDialog(null, "Modelo " + jtfModelo.getText() + " gravado com Sucesso!", "ATENÇÃO", JOptionPane.ERROR_MESSAGE, sucesso);
            limparDados();

        } catch (Exception ex) {
            GenericDAO.getInstance().rollback();
            JOptionPane.showMessageDialog(null, "Instituição já existente!" + "\n" + ex.getClass().getSimpleName() + "\n" + ex.getMessage(), "ATENÇÃO", JOptionPane.ERROR_MESSAGE, erro);
            limparDados();
        }
        jtfModelo.requestFocus();
    }//GEN-LAST:event_jbGravarActionPerformed

    private void jbSelecionarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelecionarCursoActionPerformed
        try {
            //pegando a opção selecionada na grade
            modelo = (Modelo) tabmodelo.getDadoAt(jtBusca.getSelectedRow());
            if (modelo != null) {
                jtfModelo.setText(modelo.getNmModelo());
                jcModelo.setSelectedItem(modelo.getCdMarca());
                Busca.dispose();
                jtBusca.clearSelection();
            }
        } catch (Throwable ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar a Curso/Instituição!" + "\n" + ex.getClass().getSimpleName() + "\n" + ex.getMessage(), "ATENÇÃO", JOptionPane.ERROR_MESSAGE, erro);
            limparDados();
        }
    }//GEN-LAST:event_jbSelecionarCursoActionPerformed

    private void jtfModeloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfModeloKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            carregaTabela();
            Busca.show();
            Busca.setLocationRelativeTo(this);//seta a posição da tela 
        }
    }//GEN-LAST:event_jtfModeloKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Busca;
    private javax.swing.JLabel jMarca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbGravar;
    private javax.swing.JButton jbSelecionarCurso;
    private javax.swing.JComboBox jcModelo;
    private javax.swing.JLabel jlmodelo;
    private javax.swing.JTable jtBusca;
    private javax.swing.JTextField jtfModelo;
    // End of variables declaration//GEN-END:variables
}
