/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewSisXerox.Janelas;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import NewSisXerox.Classes.ClasseImagem;

/**
 *
 * @author Allan
 */
public class JFPrincipal extends javax.swing.JFrame {

    JIFEmpresa empresa;
    JIFInstituicao instituicao;
    JIFUnidade unidade;
    JIFMarcaModelo marca;

    public JFPrincipal() {
        try {
//            Pega o padrao do windows
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
//            UIManager.setLookAndFeel("org.jvnet.substance.SubstanceLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        URL url = this.getClass().getResource("/NewSisXerox/Imagens/Icone-64.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);

        //deixando na cheia
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new ClasseImagem("/NewSisXerox/Imagens/Brazil_Flag.jpg");
        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastros = new javax.swing.JMenu();
        cadEmpresa = new javax.swing.JMenuItem();
        jmCursoInstituicao = new javax.swing.JMenuItem();
        jmUnidadeMedida = new javax.swing.JMenuItem();
        jmMarcaModelo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        Cadastros.setText("Cadastros");

        cadEmpresa.setText("Empresa");
        cadEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadEmpresaActionPerformed(evt);
            }
        });
        Cadastros.add(cadEmpresa);

        jmCursoInstituicao.setText("Curso/Instituição");
        jmCursoInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCursoInstituicaoActionPerformed(evt);
            }
        });
        Cadastros.add(jmCursoInstituicao);

        jmUnidadeMedida.setText("Unidade de Medida");
        jmUnidadeMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUnidadeMedidaActionPerformed(evt);
            }
        });
        Cadastros.add(jmUnidadeMedida);

        jmMarcaModelo.setText("Marca/Modelo");
        jmMarcaModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMarcaModeloActionPerformed(evt);
            }
        });
        Cadastros.add(jmMarcaModelo);

        jMenuBar1.add(Cadastros);

        jMenu2.setText("Utilitários");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadEmpresaActionPerformed
        try {
            if (evt.getSource() == cadEmpresa) {
                if (empresa == null) {
                    empresa = new JIFEmpresa();
                    Desktop.add(empresa);
                    empresa.setVisible(true);
                    empresa.setPosicao();//Seta centralizado
                }
                Desktop.moveToFront(empresa);
            }
            if (empresa.isClosed()) {
                empresa = new JIFEmpresa();
                Desktop.add(empresa);
                empresa.setVisible(true);
                empresa.setPosicao();//Seta centralizado
                Desktop.moveToFront(empresa);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Não foi possível abrir tela de Configurações" + "\n" + e.getMessage());
        }
    }//GEN-LAST:event_cadEmpresaActionPerformed

    private void jmCursoInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCursoInstituicaoActionPerformed
        try {
            if (evt.getSource() == jmCursoInstituicao) {
                if (instituicao == null) {
                    instituicao = new JIFInstituicao();
                    Desktop.add(instituicao);
                    instituicao.setVisible(true);
                    instituicao.setPosicao();//Seta centralizado
                }
                Desktop.moveToFront(instituicao);
            }
            if (instituicao.isClosed()) {
                instituicao = new JIFInstituicao();
                Desktop.add(instituicao);
                instituicao.setVisible(true);
                instituicao.setPosicao();//Seta centralizado
                Desktop.moveToFront(instituicao);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Não foi possível abrir tela da Instituição" + "\n" + e.getMessage());
        }
    }//GEN-LAST:event_jmCursoInstituicaoActionPerformed

    private void jmUnidadeMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUnidadeMedidaActionPerformed
        try {
            if (evt.getSource() == jmUnidadeMedida) {
                if (unidade == null) {
                    unidade = new JIFUnidade();
                    Desktop.add(unidade);
                    unidade.setVisible(true);
                    unidade.setPosicao();//Seta centralizado
                }
                Desktop.moveToFront(unidade);
            }
            if (unidade.isClosed()) {
                unidade = new JIFUnidade();
                Desktop.add(unidade);
                unidade.setVisible(true);
                unidade.setPosicao();//Seta centralizado
                Desktop.moveToFront(unidade);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Não foi possível abrir janela Unidade Medida/Marca" + "\n" + e.getMessage());
        }
    }//GEN-LAST:event_jmUnidadeMedidaActionPerformed

    private void jmMarcaModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMarcaModeloActionPerformed
          try {
            if (evt.getSource() == jmMarcaModelo) {
                if (marca == null) {
                    marca = new JIFMarcaModelo();
                    Desktop.add(marca);
                    marca.setVisible(true);
                    marca.setPosicao();//Seta centralizado
                }
                Desktop.moveToFront(unidade);
            }
            if (marca.isClosed()) {
                marca = new JIFMarcaModelo();
                Desktop.add(marca);
                marca.setVisible(true);
                marca.setPosicao();//Seta centralizado
                Desktop.moveToFront(marca);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Não foi possível abrir janela Unidade Medida/Marca" + "\n" + e.getMessage());
        }
    }//GEN-LAST:event_jmMarcaModeloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cadastros;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem cadEmpresa;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmCursoInstituicao;
    private javax.swing.JMenuItem jmMarcaModelo;
    private javax.swing.JMenuItem jmUnidadeMedida;
    // End of variables declaration//GEN-END:variables
}
